version: '3.0'

services: 
    round2:
        image: node:latest
        working_dir: /liteServ
        volumes:
        - ./:/liteServ
        ports: 
        - 7000:3000
        entrypoint: ["./script_pipe.sh", ""]
        #command: bash script_pipe.sh